#!/usr/bin/perl

$usage = "usage: datify [YYYY-MM-DD] file1 [file2 file3 ...]

prefixes file foo using today's date as YYYY-MM-DDfoo

if no date is give, today's date is used.
";

if ($ARGV[0] =~ m/^(\d\d\d\d)-(\d\d)-(\d\d)$/) {
    $year = $1;
    $month = $2;
    $day = $3;
    shift @ARGV;
} 
else {
    ($day,$month,$year) = (localtime)[3,4,5];
    $year = $year + 1900;
    $month = $month+1;
    if ($month < 10) {
	$month = "0$month";
    }
    if ($day < 10) {
	$day = "0$day";
    }
}

foreach $file (@ARGV) {
    $newfile = "$year-$month-$day$file";
    # replace spaces with underscores
    $newfile =~ s/ +/_/g;
    # remove parentheses
    $newfile =~ s/\(//g;
    $newfile =~ s/\)//g;

    $file =~ s/ /\\ /g;
    `mv -i "$file" "$newfile"`;
    print "moved $file to $newfile\n";
}
